version: '2'
services:
    web:
        build: .
        container_name: magento2devbox_web
        restart: always
        volumes:
          - "../shared/webroot:/home/magento2/magento2"
          - "~/.composer:/home/magento2/.composer"
          - "~/.ssh:/home/magento2/.ssh"
          - "../shared/logs/apache2:/var/log/apache2"
          - "../shared/logs/php-fpm:/var/log/php-fpm"
          - "../shared/.magento-cloud:/home/magento2/.magento-cloud"
        environment:
          - USE_SHARED_WEBROOT=0
          - SHARED_CODE_PATH="/home/magento2/magento2"
          - USE_RABBITMQ=0
          - USE_REDIS_FULL_PAGE_CACHE=0
          - USE_REDIS_CACHE=1
          - USE_REDIS_SESSIONS=1
          - USE_VARNISH=0
          - USE_ELASTICSEARCH=0
          - MAGENTO_PUBLIC_KEY=d738dbd718aa6cd2fecbf956bc4fb0cd
          - MAGENTO_PRIVATE_KEY=028509eaf0da0e47d5ca07329f955175
          - MAGENTO_USE_SOURCES_IN_HOST=0
          - CREATE_SYMLINK_EE=0
          - HOST_CE_PATH=../shared/webroot
          - EE_DIRNAME=magento2ee
          - MAGENTO_DOWNLOAD_SOURCES_COMPOSER=1
          - MAGENTO_EDITION=ce
          - MAGENTO_VERSION=2.1.6
          - MAGENTO_SAMPLE_DATA_INSTALL=0
          - MAGENTO_DOWNLOAD_SOURCES_CLOUD=0
          - MCLOUD_USERNAME=
          - MCLOUD_PASSWORD=
          - MCLOUD_GENERATE_NEW_TOKEN=
          - MCLOUD_PROJECT=
          - MCLOUD_BRANCH=
          - MAGENTO_CRON_RUN=0
          - MAGENTO_DI_COMPILE=0
          - MAGENTO_GRUNT_COMPILE=0
          - MAGENTO_STATIC_CONTENTS_DEPLOY=0
          - MAGENTO_BACKEND_PATH=admin
          - MAGENTO_ADMIN_USER=lsretail
          - MAGENTO_ADMIN_PASSWORD=lsr3t41l
        ports:
          - "80"
          - "22"

    db:
        container_name: magento2devbox_db
        restart: always
        image: mysql:5.6
        ports:
          - "3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento2
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"

    redis:
        container_name: magento2devbox_redis
        restart: always
        image: redis:3.0.7
